# -*- coding: utf-8 -*-
"""model_summarize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjypJ2SiX-FH97Ng-LSpN7vN6mViFKBp
"""

# !pip install openai transformers

from transformers import pipeline
import textwrap

# Inisialisasi model BART
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# Input dari pengguna
user_text = input("Masukkan teks yang ingin diringkas:\n")

# Ringkasan oleh BART
bart_summary = summarizer(user_text, max_length=150, min_length=40, do_sample=False)[0]['summary_text']

# Tampilkan hasil ringkasan dengan pembungkusan teks
print("\nRingkasan oleh BART:")
print("=" * 50)
print(textwrap.fill(bart_summary, width=80))  # Bungkus 80 karakter per baris
print("=" * 50)