# -*- coding: utf-8 -*-
"""model_summarize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjypJ2SiX-FH97Ng-LSpN7vN6mViFKBp
"""


from transformers import pipeline, BartTokenizer, BartForConditionalGeneration
import textwrap

# Load tokenizer dan model untuk disimpan nanti
tokenizer = BartTokenizer.from_pretrained("facebook/bart-large-cnn")
model = BartForConditionalGeneration.from_pretrained("facebook/bart-large-cnn")

# Simpan model dan tokenizer supaya bisa dipakai offline nanti
save_path = "./saved_bart_model"
tokenizer.save_pretrained(save_path)
model.save_pretrained(save_path)
print(f"Model dan tokenizer disimpan di folder: {save_path}")

# Buat pipeline ringkasan dari model yang baru saja di-load
summarizer = pipeline("summarization", model=model, tokenizer=tokenizer)

# Input teks dari user
user_text = input("Masukkan teks yang ingin diringkas:\n")

# Buat ringkasan
bart_summary = summarizer(user_text, max_length=150, min_length=40, do_sample=False)[0]['summary_text']

# Tampilkan ringkasan dengan pembungkusan teks
print("\nRingkasan oleh BART:")
print("=" * 50)
print(textwrap.fill(bart_summary, width=80))
print("=" * 50)
