# -*- coding: utf-8 -*-
"""model_summarize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjypJ2SiX-FH97Ng-LSpN7vN6mViFKBp
"""

import streamlit as st
from transformers import pipeline
import textwrap

st.title("Ringkasan Teks dengan BART")

# Inisialisasi pipeline summarization (model facebook/bart-large-cnn)
@st.cache_resource(show_spinner=False)
def load_summarizer():
    return pipeline("summarization", model="facebook/bart-large-cnn")

summarizer = load_summarizer()

# Text input dari pengguna
user_text = st.text_area("Masukkan teks yang ingin diringkas:")

if st.button("Ringkas"):
    if user_text.strip():
        summary = summarizer(user_text, max_length=150, min_length=40, do_sample=False)[0]['summary_text']
        st.subheader("Hasil Ringkasan:")
        st.write(textwrap.fill(summary, width=80))
    else:
        st.warning("Silakan masukkan teks terlebih dahulu.")

